const globals = require("globals");

module.exports = [
  {
    files: ["modules/monitoring/templates/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        ...globals.browser,
        ...globals.es2021,
        ApexCharts: "readonly",
        expandedElements: "writable",
        currentTab: "writable",
        charts: "writable",
        currentTelemetry: "writable",
        rollingTelemetryBuffer: "writable",
        chartWindowMinutes: "writable",
        lastChartStates: "writable",
        fullTaskHistory: "writable",
        lastStatusData: "writable",
        refreshEnabled: "writable",
        COLORS: "readonly",
        getHwIconAndLabel: "readonly",
        escapeHtml: "readonly",
        downloadSrt: "readonly",
        downloadSrtById: "readonly",
        formatDur: "readonly",
        formatDDHHMMSS: "readonly",
        getTimerText: "readonly",
        showTab: "readonly",
        handleToggle: "readonly",
        saveSettings: "readonly",
        renderAuditDetails: "readonly",
        renderHistory: "readonly",
        toggleRefresh: "readonly",
        updateStats: "readonly",
        changeChartWindow: "readonly",
        renderCharts: "readonly",
        createOrUpdateLineChart: "readonly",
        formatDuration: "readonly",
        fetchAnalytics: "readonly",
        renderAnalytics: "readonly",
        updateOrCreateChart: "readonly",
        exportJson: "readonly",
        rawData: "writable",
      },
    },
    rules: {
      "no-undef": "error",
      eqeqeq: ["error", "always"],
      "no-var": "error",
    },
  },
  {
    files: ["tests/js/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
      globals: {
        ...globals.node,
        ...globals.es2021,
        describe: "readonly",
        it: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        vi: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "error",
      "no-undef": "error",
      eqeqeq: ["error", "always"],
      "no-var": "error",
      "prefer-const": "error",
    },
  },
];
