"""Coverage for the fixture-generation voice cache.

The audio matrix is regenerated rarely and on someone's machine, so a cache that looks
complete but is not costs a full synthesis run before it says so.
"""

from pathlib import Path
from unittest import mock

import pytest

from scripts.audio_matrix import piper


def _voice(cache: Path, name: str, *, sidecar: bool) -> Path:
    model = piper.voice_dir(cache)
    model.mkdir(parents=True, exist_ok=True)
    onnx = model / f"{name}.onnx"
    onnx.write_bytes(b"model-bytes")
    if sidecar:
        onnx.with_suffix(".onnx.json").write_text("{}", encoding="utf-8")
    return onnx


class TestEnsuringAVoiceIsCached:
    """A voice is usable only when both halves of it are on disk and verified."""

    def test_a_complete_cache_is_not_redownloaded(self, tmp_path):
        """Voices are large and the matrix is regenerated by hand."""
        _voice(tmp_path, "en_US-lessac", sidecar=True)
        with mock.patch.object(piper, "download_voice") as download:
            piper.ensure_voice(tmp_path, "en_US-lessac", expected_md5="")
        download.assert_not_called()

    def test_a_cache_missing_the_json_sidecar_is_redownloaded(self, tmp_path):
        """The recorded defect: piper reads <voice>.onnx.json for the phoneme map and sample
        rate, so a cache holding only the .onnx passed this check and then failed inside
        synthesis -- once per clip, naming neither the voice nor the missing sidecar."""
        _voice(tmp_path, "en_US-lessac", sidecar=False)
        with mock.patch.object(piper, "download_voice") as download:
            piper.ensure_voice(tmp_path, "en_US-lessac", expected_md5="")
        download.assert_called_once()

    def test_an_absent_voice_is_downloaded(self, tmp_path):
        """The ordinary first-run path."""
        with mock.patch.object(piper, "download_voice") as download:
            piper.ensure_voice(tmp_path, "en_US-lessac", expected_md5="")
        download.assert_called_once()

    def test_a_checksum_mismatch_is_refused_with_a_recoverable_message(self, tmp_path):
        """A corrupt voice must name the file to delete, or the caller cannot act on it."""
        onnx = _voice(tmp_path, "en_US-lessac", sidecar=True)
        with mock.patch.object(piper, "download_voice"), pytest.raises(ValueError) as err:
            piper.ensure_voice(tmp_path, "en_US-lessac", expected_md5="not-the-real-digest")
        # The message has to name the file to delete, or the caller cannot act on it.
        assert str(onnx) in str(err.value)

    def test_a_matching_checksum_is_accepted(self, tmp_path):
        """A verified cache hit returns the model path unchanged."""
        onnx = _voice(tmp_path, "en_US-lessac", sidecar=True)
        with mock.patch.object(piper, "download_voice"):
            assert piper.ensure_voice(tmp_path, "en_US-lessac", expected_md5=piper.file_md5(onnx)) == onnx
